# Generated by Django 3.1 on 2020-09-24 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
