# Generated by Django 3.1 on 2020-09-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
