# Generated by Django 3.1 on 2020-09-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200928_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='product_title',
        ),
    ]
