# Generated by Django 3.1 on 2020-10-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_watchlist_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watch_related',
            field=models.ManyToManyField(related_name='watchlist_realted', to='auctions.Watchlist'),
        ),
    ]
